name: nixos-tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
   branches:
     - main

jobs:
  nixos-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix flake check -L
